package com.utbm.keepit.backend.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.utbm.keepit.backend.entity.Exercise;
import com.utbm.keepit.backend.entity.JoinSeanceExercise;
import com.utbm.keepit.backend.entity.JoinTopicExercise;
import com.utbm.keepit.backend.entity.Seance;
import com.utbm.keepit.backend.entity.Topic;
import com.utbm.keepit.backend.entity.User;

import com.utbm.keepit.backend.dao.ExerciseDao;
import com.utbm.keepit.backend.dao.JoinSeanceExerciseDao;
import com.utbm.keepit.backend.dao.JoinTopicExerciseDao;
import com.utbm.keepit.backend.dao.SeanceDao;
import com.utbm.keepit.backend.dao.TopicDao;
import com.utbm.keepit.backend.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exerciseDaoConfig;
    private final DaoConfig joinSeanceExerciseDaoConfig;
    private final DaoConfig joinTopicExerciseDaoConfig;
    private final DaoConfig seanceDaoConfig;
    private final DaoConfig topicDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ExerciseDao exerciseDao;
    private final JoinSeanceExerciseDao joinSeanceExerciseDao;
    private final JoinTopicExerciseDao joinTopicExerciseDao;
    private final SeanceDao seanceDao;
    private final TopicDao topicDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exerciseDaoConfig = daoConfigMap.get(ExerciseDao.class).clone();
        exerciseDaoConfig.initIdentityScope(type);

        joinSeanceExerciseDaoConfig = daoConfigMap.get(JoinSeanceExerciseDao.class).clone();
        joinSeanceExerciseDaoConfig.initIdentityScope(type);

        joinTopicExerciseDaoConfig = daoConfigMap.get(JoinTopicExerciseDao.class).clone();
        joinTopicExerciseDaoConfig.initIdentityScope(type);

        seanceDaoConfig = daoConfigMap.get(SeanceDao.class).clone();
        seanceDaoConfig.initIdentityScope(type);

        topicDaoConfig = daoConfigMap.get(TopicDao.class).clone();
        topicDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        exerciseDao = new ExerciseDao(exerciseDaoConfig, this);
        joinSeanceExerciseDao = new JoinSeanceExerciseDao(joinSeanceExerciseDaoConfig, this);
        joinTopicExerciseDao = new JoinTopicExerciseDao(joinTopicExerciseDaoConfig, this);
        seanceDao = new SeanceDao(seanceDaoConfig, this);
        topicDao = new TopicDao(topicDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Exercise.class, exerciseDao);
        registerDao(JoinSeanceExercise.class, joinSeanceExerciseDao);
        registerDao(JoinTopicExercise.class, joinTopicExerciseDao);
        registerDao(Seance.class, seanceDao);
        registerDao(Topic.class, topicDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        exerciseDaoConfig.clearIdentityScope();
        joinSeanceExerciseDaoConfig.clearIdentityScope();
        joinTopicExerciseDaoConfig.clearIdentityScope();
        seanceDaoConfig.clearIdentityScope();
        topicDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ExerciseDao getExerciseDao() {
        return exerciseDao;
    }

    public JoinSeanceExerciseDao getJoinSeanceExerciseDao() {
        return joinSeanceExerciseDao;
    }

    public JoinTopicExerciseDao getJoinTopicExerciseDao() {
        return joinTopicExerciseDao;
    }

    public SeanceDao getSeanceDao() {
        return seanceDao;
    }

    public TopicDao getTopicDao() {
        return topicDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
